DROP TABLE users;
CREATE TABLE users (id MEDIUMINT NOT NULL AUTO_INCREMENT, username TEXT NOT NULL, password TEXT NOT NULL, salt TEXT NOT NULL, levels TEXT NOT NULL, hints MEDIUMINT NOT NULL, PRIMARY KEY(id));
